"""
Domain models for SUS — Spike Understanding System.

Pydantic models representing the core product concepts. These models serve as
the contract between layers: API ↔ Service ↔ Domain.

Design principles:
- Models are serializable (JSON-safe for API responses).
- IDs use str (UUIDs when persistence is added; deterministic strings for now).
- Timestamps are ISO 8601 strings for simplicity.
- No pandas or ML objects leak into domain models.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field

from src.domain.enums import (
    ConfidenceBand,
    IncidentSeverity,
    IncidentStatus,
    InvestigationStatus,
    PipelineClassification,
)


# ---------------------------------------------------------------------------
# Merchant
# ---------------------------------------------------------------------------

class Merchant(BaseModel):
    """Represents a monitored merchant in the SUS system."""

    id: str = Field(..., description="Unique merchant identifier, e.g. 'merchant_001'")
    name: str = Field(..., description="Display name for the merchant")
    daily_volume: int = Field(..., description="Baseline daily transaction volume")
    risk_level: str = Field("low", description="Current risk level: low, medium, high")


# ---------------------------------------------------------------------------
# Activity Event
# ---------------------------------------------------------------------------

class BehavioralEvidence(BaseModel):
    """A single behavioral evidence signal for an anomaly."""

    feature: str = Field(..., description="Feature name, e.g. 'failed_payment_rate'")
    label: str = Field(..., description="Human-readable label")
    normal_value: float = Field(..., description="Baseline normal value")
    current_value: float = Field(..., description="Current observed value")
    change_percent: float = Field(..., description="Percentage change from normal")
    signal_type: str = Field(..., description="fraud, organic, or neutral")


class ActivityEvent(BaseModel):
    """A single detected activity event (anomaly/spike) on the timeline."""

    id: str = Field(..., description="Unique event identifier")
    merchant_id: str = Field(..., description="Merchant this event belongs to")
    date: str = Field(..., description="Date of the event (ISO 8601)")
    status: PipelineClassification = Field(
        ..., description="Pipeline classification result"
    )
    severity: IncidentSeverity = Field(
        ..., description="Severity level"
    )
    transaction_count: int = Field(..., description="Transaction count in this window")
    baseline_volume: int = Field(..., description="Expected baseline volume")
    z_score: float = Field(..., description="Volume z-score (anomaly magnitude)")
    fraud_probability: float = Field(..., description="Model's fraud probability")
    confidence: float = Field(..., description="Model confidence score")
    confidence_band: ConfidenceBand = Field(
        ..., description="Confidence band classification"
    )
    summary: str = Field("", description="Human-readable anomaly summary")
    evidence: list[BehavioralEvidence] = Field(
        default_factory=list, description="Behavioral evidence signals"
    )


# ---------------------------------------------------------------------------
# Incident
# ---------------------------------------------------------------------------

class Incident(BaseModel):
    """A structured incident record generated by the SUS pipeline.

    Incidents are created for fraud_spike and review_required windows.
    """

    id: str = Field(..., description="Deterministic incident ID, e.g. 'INC-merchant_001-20250724'")
    merchant_id: str = Field(..., description="Merchant this incident belongs to")
    date: str = Field(..., description="Date of the triggering event")
    severity: IncidentSeverity = Field(..., description="Severity classification")
    status: IncidentStatus = Field(
        IncidentStatus.OPEN, description="Current operational status"
    )
    classification: PipelineClassification = Field(
        ..., description="Pipeline classification"
    )
    predicted_cause: Optional[str] = Field(
        None, description="Predicted cause label from Stage 2"
    )
    fraud_probability: float = Field(
        ..., description="Model fraud probability [0, 1]"
    )
    confidence: float = Field(..., description="Model confidence score [0, 1]")
    confidence_band: ConfidenceBand = Field(..., description="Confidence band")
    anomaly_score: float = Field(
        ..., description="Volume z-score from Stage 1"
    )
    decision_reason: str = Field(
        "", description="Human-readable decision rationale"
    )
    anomaly_summary: str = Field(
        "", description="Summary of detected behavioral anomalies"
    )
    top_signals: list[str] = Field(
        default_factory=list, description="Most relevant evidence signals"
    )
    recommended_action: str = Field(
        "", description="System-recommended action"
    )
    created_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="Record creation timestamp (ISO 8601)",
    )


# ---------------------------------------------------------------------------
# Pipeline Summary
# ---------------------------------------------------------------------------

class PipelineSummary(BaseModel):
    """Aggregate statistics from a pipeline run.

    Provides a high-level view of what the pipeline found across all
    merchant-day windows in a given dataset.
    """

    total_windows: int = Field(..., description="Total merchant-day windows processed")
    spikes_detected: int = Field(..., description="Number of spikes detected by Stage 1")
    spike_rate: float = Field(..., description="Fraction of windows flagged as spikes")
    fraud_incidents: int = Field(..., description="High-confidence fraud classifications")
    organic_incidents: int = Field(..., description="High-confidence organic classifications")
    review_required: int = Field(..., description="Ambiguous/low-confidence cases")
    baseline_windows: int = Field(..., description="Windows with no anomaly detected")


# ---------------------------------------------------------------------------
# Investigation
# ---------------------------------------------------------------------------

class Investigation(BaseModel):
    """Groups one or more incidents under a single analyst investigation.

    An investigation provides a unified view of related anomalies,
    evidence, and recommended actions.
    """

    id: str = Field(..., description="Unique investigation identifier")
    status: InvestigationStatus = Field(
        InvestigationStatus.INITIATED, description="Investigation workflow status"
    )
    title: str = Field("", description="Short human-readable title")
    summary: str = Field("", description="Investigation narrative")
    merchant_ids: list[str] = Field(
        default_factory=list, description="Merchants under investigation"
    )
    incident_ids: list[str] = Field(
        default_factory=list, description="Related incident IDs"
    )
    incidents: list[Incident] = Field(
        default_factory=list, description="Full incident records"
    )
    created_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="Creation timestamp",
    )
    updated_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="Last update timestamp",
    )
