"""
SQLAlchemy ORM models for SUS — Spike Understanding System.

Defines the database schema for persisted investigation runs and incidents.
Uses SQLAlchemy 2.x typed mapping style with Mapped and mapped_column.

Important: These ORM models are named differently from domain models to
avoid naming conflicts:
- InvestigationRun (not Investigation) → investigation_runs table
- PersistedIncident (not Incident) → persisted_incidents table
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import Float, ForeignKey, Index, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.database.base import Base


# ---------------------------------------------------------------------------
# Investigation Run
# ---------------------------------------------------------------------------


class InvestigationRun(Base):
    """One row per POST /investigations/run execution.

    Records the pipeline execution parameters, summary statistics,
    and links to all incidents generated during that run.
    """

    __tablename__ = "investigation_runs"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Business identifier (e.g. "INV-XXXXXXXXXXXX")
    investigation_id: Mapped[str] = mapped_column(
        String(64), unique=True, nullable=False, index=True
    )

    # Run status
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="completed"
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # Input parameters
    transactions_path: Mapped[str] = mapped_column(String(512), nullable=False)
    window_labels_path: Mapped[str] = mapped_column(String(512), nullable=False)
    model_path: Mapped[Optional[str]] = mapped_column(String(512), nullable=True)
    z_threshold: Mapped[float] = mapped_column(Float, nullable=False)
    min_history_days: Mapped[int] = mapped_column(Integer, nullable=False)
    merchant_filter: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)

    # Pipeline summary fields
    total_results: Mapped[int] = mapped_column(Integer, nullable=False)
    spikes_detected: Mapped[int] = mapped_column(Integer, nullable=False)
    fraud_incidents: Mapped[int] = mapped_column(Integer, nullable=False)
    organic_incidents: Mapped[int] = mapped_column(Integer, nullable=False)
    review_required: Mapped[int] = mapped_column(Integer, nullable=False)
    baseline_windows: Mapped[int] = mapped_column(Integer, nullable=False)
    spike_rate: Mapped[float] = mapped_column(Float, nullable=False)
    processing_note: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Relationship to incidents
    incidents: Mapped[list["PersistedIncident"]] = relationship(
        back_populates="investigation_run",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        return f"<InvestigationRun {self.investigation_id} status={self.status}>"


# ---------------------------------------------------------------------------
# Persisted Incident
# ---------------------------------------------------------------------------


class PersistedIncident(Base):
    """One row per incident generated by a pipeline run.

    Named PersistedIncident to avoid collision with the existing
    Incident dataclass in src/incidents.py and the Pydantic Incident
    model in src/domain/models.py.
    """

    __tablename__ = "persisted_incidents"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Foreign key to parent investigation run
    investigation_run_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("investigation_runs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Incident identity
    incident_id: Mapped[str] = mapped_column(
        String(128), nullable=False, index=True
    )
    merchant_id: Mapped[str] = mapped_column(
        String(128), nullable=False, index=True
    )
    date: Mapped[str] = mapped_column(String(16), nullable=False)

    # Classification
    severity: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="open")
    classification: Mapped[str] = mapped_column(
        String(32), nullable=False, index=True
    )
    predicted_cause: Mapped[Optional[str]] = mapped_column(String(256), nullable=True)

    # Scores
    fraud_probability: Mapped[float] = mapped_column(Float, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    confidence_band: Mapped[str] = mapped_column(String(32), nullable=False)
    anomaly_score: Mapped[float] = mapped_column(Float, nullable=False)

    # Evidence
    decision_reason: Mapped[str] = mapped_column(Text, nullable=False, default="")
    anomaly_summary: Mapped[str] = mapped_column(Text, nullable=False, default="")
    top_signals_json: Mapped[str] = mapped_column(
        Text, nullable=False, default="[]"
    )
    recommended_action: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Analyst workflow metadata
    workflow_status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="open", index=True
    )
    assigned_analyst: Mapped[Optional[str]] = mapped_column(
        String(128), nullable=True
    )
    analyst_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    resolution: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationship back to investigation run
    investigation_run: Mapped["InvestigationRun"] = relationship(
        back_populates="incidents",
    )

    # Status history
    status_history: Mapped[list["IncidentStatusHistory"]] = relationship(
        back_populates="incident",
        cascade="all, delete-orphan",
        order_by="IncidentStatusHistory.created_at",
    )

    # Composite indexes for common query patterns
    __table_args__ = (
        Index("ix_incidents_merchant_date", "merchant_id", "date"),
        Index(
            "ix_incidents_classification_severity",
            "classification",
            "severity",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<PersistedIncident {self.incident_id} "
            f"severity={self.severity} classification={self.classification} "
            f"workflow={self.workflow_status}>"
        )


# ---------------------------------------------------------------------------
# Incident Status History
# ---------------------------------------------------------------------------


class IncidentStatusHistory(Base):
    """Audit trail for workflow status transitions on an incident.

    Records each time an analyst changes the workflow_status of an incident.
    Only created when workflow_status actually changes (not on every update).
    """

    __tablename__ = "incident_status_history"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Foreign key to parent incident
    incident_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("persisted_incidents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Transition details
    old_status: Mapped[str] = mapped_column(String(32), nullable=False)
    new_status: Mapped[str] = mapped_column(String(32), nullable=False)
    changed_by: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)
    note: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Timestamp
    created_at: Mapped[datetime] = mapped_column(
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # Relationship back to incident
    incident: Mapped["PersistedIncident"] = relationship(
        back_populates="status_history",
    )

    def __repr__(self) -> str:
        return (
            f"<IncidentStatusHistory {self.old_status} → {self.new_status} "
            f"by={self.changed_by}>"
        )
