"""Incident list API route."""

from __future__ import annotations

import logging
from typing import Optional

from fastapi import APIRouter, Query

from src.api.schemas.incidents import IncidentListItem, IncidentListResponse
from src.services.incident_service import get_incidents

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/incidents", tags=["incidents"])


@router.get("", response_model=IncidentListResponse)
async def list_incidents(
    merchant_id: Optional[str] = Query(None, description="Filter by merchant ID"),
    severity: Optional[str] = Query(None, description="Filter by severity"),
    classification: Optional[str] = Query(None, description="Filter by classification"),
    status: Optional[str] = Query(None, description="Filter by status"),
    limit: Optional[int] = Query(None, ge=1, le=500),
) -> IncidentListResponse:
    """Get incidents.

    Returns incidents generated by the pipeline for fraud and review-required windows.
    """
    incidents = get_incidents(
        merchant_id=merchant_id,
        severity=severity,
        classification=classification,
        status=status,
        limit=limit,
    )

    items = [IncidentListItem(**i) for i in incidents]
    return IncidentListResponse(incidents=items, total=len(items))
